# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Wallet SDK Documentation
site_url: "https://vbmobile.github.io/mobile-id-wallet-documentation/"
use_directory_urls: false
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
        info: octicons/info-16
  logo: assets/vb-logo.png
  favicon: assets/vb-favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - content.code.copy
  palette:
      primary: light blue
      accent: blue
extra:
  version:
    provider:
      mike
extra_css:
  - stylesheets/extra.css
nav:
  - Getting started: index.md
  - Features:
    - Common:
        - How to handle errors: Features/Common/HandleErrors.md
        - Use compose for custom views: Features/Common/ComposeSupport.md
    - Document reader:
        - Overview: Features/DocumentReader/DocumentReader_Index.md
        - Regula database: Features/DocumentReader/DocumentReader_RegulaDB.md
        - Customization:
            - Loading view: Features/DocumentReader/DocumentReader_LoadingView.md
            - Scan view: Features/DocumentReader/DocumentReader_ScanView.md
            - RFID read view: Features/DocumentReader/DocumentReader_HandleErrors.md
            - Chip reading:
                - iOS:
                    - Read chip view: Features/DocumentReader/DocumentReader_ReadChipView_iOS.md
                - Android:
                    - Find chip view: Features/DocumentReader/DocumentReader_FindChipView_Android.md
                    - Read chip view: Features/DocumentReader/DocumentReader_ReadChipView_Android.md
            - Preview view: Features/DocumentReader/DocumentReader_PreviewView.md
        - Handle errors: Features/DocumentReader/DocumentReader_HandleErrors.md
    - Face capture:
        - Overview: Features/FaceCapture/FaceCapture_Index.md
        - Customization:
            - Loading view: Features/FaceCapture/FaceCapture_LoadingView.md
            - Scan view: Features/FaceCapture/FaceCapture_ScanView.md
            - Preview view: Features/FaceCapture/FaceCapture_PreviewView.md
        - Handle errors: Features/FaceCapture/FaceCapture_HandleErrors.md
    - Biometric match:
        - Overview: Features/BiometricMatch/BiometricMatch_Index.md
        - Customization:
            - Loading view: Features/BiometricMatch/BiometricMatch_LoadingView.md
        - Handle errors: Features/BiometricMatch/BiometricMatch_HandleErrors.md
    - Boarding pass reader:
        - Overview: Features/BoardingPass/BoardingPass_Index.md
        - Customization:
            - Loading view: Features/BoardingPass/BoardingPass_LoadingView.md
            - Scan view: Features/BoardingPass/BoardingPass_ScanView.md
            - Preview view: Features/BoardingPass/BoardingPass_PreviewView.md
        - Handle errors: Features/BoardingPass/BoardingPass_HandleErrors.md
    - Subject management:
        - Overview: Features/SubjectManagement/SubjectManagement_Index.md
        - Customization:
            - Loading view: Features/SubjectManagement/SubjectManagement_LoadingView.md
        - Handle errors: Features/SubjectManagement/SubjectManagement_HandleErrors.md
    - Form: Features/Form/Form_Index.md
  - Release notes:
    - Android: ReleaseNotes/ReleaseNotes_Android.md
    - iOS: ReleaseNotes/ReleaseNotes_iOS.md
  - Migration guide:
    - Android: MigrationGuide/MigrationGuide_Android.md
    - iOS: MigrationGuide/MigrationGuide_iOS.md
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
repo_url: https://github.com/vbmobile?tab=repositories
repo_name: Sample Apps
