# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Wallet SDK Documentation
site_url: "https://vbmobile.github.io/mobile-id-wallet-documentation/"
use_directory_urls: false
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
        info: octicons/info-16
  logo: assets/vb-logo.png
  favicon: assets/vb-favicon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - content.tabs.link
    - content.code.copy
  palette:
      primary: white
      accent: indigo
extra:
  version:
    provider:
      mike
extra_css:
  - stylesheets/extra.css
nav:
  - Getting started: index.md
  - Features:
    - MobileIdWalletSDK:
      - Intro: Features/MobileIdWalletSDK/Intro/Index.md
      - Documents: Features/MobileIdWalletSDK/Documents/Index.md
      - Boarding Passes: Features/MobileIdWalletSDK/BoardingPasses/Index.md
      - Subject Management: Features/MobileIdWalletSDK/SubjectManagement/Index.md
      - Misc: Features/MobileIdWalletSDK/Misc/Index.md
    #- MobileIdWalletUISDK:
    #  - Intro: Features/MobileIdWalletUISDK/Intro/Index.md
    #  - Sharing Credentials: Features/MobileIdWalletUISDK/SharingCredentials/Index.md
            
  - Release notes:
    - Android: ReleaseNotes/ReleaseNotes_Android.md
    - iOS: ReleaseNotes/ReleaseNotes_iOS.md
  #- Migration guide:
  #  - Android: MigrationGuide/MigrationGuide_Android.md
  #  - iOS: MigrationGuide/MigrationGuide_iOS.md
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
repo_url: https://github.com/vbmobile?tab=repositories
repo_name: Sample Apps